### ISSUE TITLE
[Bug] Time selector dropdown width is broken

### ISSUE THREAD

**Issue by kukukaka** [tinybirdco/web-analytics-starter-kit#23]
### Module

Dashboard

### Describe the Bug

The dropdown to select the time range is not displaying correctly. It's not wide enough.

![Screenshot 2022-09-22 at 09 41 43](https://user-images.githubusercontent.com/8354661/191716879-ab99f51d-4c6d-401c-a0b3-6077cf485a85.png)
wide

### Expected Behavior

The dropdown arrow should not overlap with the text label.

### To Reproduce

Just access any pre-built analytics dashboard.

### Details

Might the bug be coming from this change?

![Screenshot 2022-09-22 at 09 45 55](https://user-images.githubusercontent.com/8354661/191717269-dd3e8268-b46a-4d4a-8216-517203906b59.png)

**Comment by alejandromav** [comment]
I think the last few commits from @rmorehig almost solved this, but I still see some issues with the mobile version:

![image](https://user-images.githubusercontent.com/3041948/191783251-2f948e7c-0509-4a03-8e2b-8340edcaf6a9.png)

**Comment by kukukaka** [comment]
Thanks!

The dropdown width issue is solved. I will open a different ticket to review the mobile layout.
