### ISSUE TITLE
[Bug] For users outside of Europe the entire app is non-functional unless you manually adjust the date.

### ISSUE THREAD

**Issue by grempe** [tinybirdco/web-analytics-starter-kit#25]
### Module

Dashboard

### Describe the Bug

The next.js web UI for tinybirds analytics is broken for users that are not in Europe.  It will not show any data except for the 'users in the last 30 minutes' widget.

Per @tb-peregrine 

> This is actually a bug that we're aware of - the time select defaults to UTC - not local time, so when you select "Today" you're seeing tomorrow when it gets late in the day in the US. If you update the time selector, it should fix the problem.

Here's the full conversation in Slack:

![Screen Shot 2022-09-26 at 18 06 26 PM](https://user-images.githubusercontent.com/117/192389425-832f435d-9b37-4e52-9b95-3c831e11c640.png)

### Expected Behavior

All expected data should be shown.

### To Reproduce

Load the web UI in the United States.

**Comment by alejandromav** [comment]
Hi @grempe! 

First of all, **thanks a lot for testing the Starter Kit**, and taking the time to open these very useful issues.

We are on it, and we'll keep you posted here.

Thanks again, and sorry for the inconvenience 🙏

**Comment by alejandromav** [comment]
Hi @grempe, this should be now solved, thanks to @rmorehig.

I'll check tonight, when dates in UTC and EST are different, just to be 100% sure.

**Comment by grempe** [comment]
Possible typo. 

https://github.com/tinybirdco/web-analytics-starter-kit/pull/26#discussion_r981128102

**Comment by grempe** [comment]
I am seeing the dashboard display data correctly now. Thx
