### ISSUE TITLE
[Bug] Table and Plots Fail to Sync After Time Period Change

### ISSUE THREAD

**Issue by pelayoarbues** [tinybirdco/web-analytics-starter-kit#86]
### Module

Dashboard

### Describe the Bug

When adjusting the time period, the table correctly displays data for the newly selected period. However, the accompanying plots (time series, top sources, pages, etc.) do not update to reflect this change.

### Expected Behavior

After selecting a new time period, both the tables and all associated plots should update to display data for the chosen timeframe.

### To Reproduce

Just change the period in the selector :)

**Comment by alejandromav** [comment]
Hey @pelayoarbues, thanks for reporting this. I can indeed reproduce it, and we're working on a fix already.

Sorry for the inconvenience.

**Comment by pelayoarbues** [comment]
Thanks!!! 🤟🤟🤟
